name: Build and Release Vaadin Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Oracle JDK 21
        uses: oracle-actions/setup-java@v1
        with:
          website: oracle.com
          release: 21

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.8

      - name: Build with Gradle
        run: gradle clean build -Pvaadin.productionMode --stacktrace

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/libs/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
